//! MCP client pairing and per-connection authorization (phase B, ORQ-29).
//!
//! - Clients pair once with a random token generated by the app. Only a
//!   SHA-256 hash is kept in memory; the raw token is shown to the user a
//!   single time and never written to disk, WebDAV or the repository.
//! - A paired client holds no power until the user grants it access to one
//!   specific connection generation. Grants bind (client, connection,
//!   generation) so a reconnect of the same host never inherits old access.
//! - Every grant records the output sequence at authorization time; agents
//!   can only read output produced after the grant, never scrollback from
//!   before it.
//! - Revocation is immediate and monotonic (`revocation_counter` bumps
//!   invalidate in-flight checks).

use serde::Serialize;
use sha2::{Digest, Sha256};
use std::collections::HashMap;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Mutex;

fn now_ms() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

fn hash_token(token: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(token.as_bytes());
    format!("{:x}", hasher.finalize())
}

#[derive(Debug, Clone)]
pub struct PairedClient {
    pub client_id: String,
    /// Human-readable name captured at pairing time. Used for display only;
    /// never for identity decisions (clients could lie about it).
    pub label: Option<String>,
    token_hash: String,
    pub created_at_ms: u64,
}

#[derive(Debug, Clone)]
#[allow(dead_code)] // retained as phase B/C integration surface
pub struct ConnectionGrant {
    pub grant_id: String,
    pub client_id: String,
    pub connection_id: String,
    pub generation: u64,
    /// First output sequence the client may read for this connection.
    pub grant_start_seq: u64,
    pub created_at_ms: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AuthError {
    UnknownClient,
    BadToken,
    NoGrant,
    StaleGeneration,
}

struct AuthInner {
    clients: HashMap<String, PairedClient>,
    /// grants keyed by (client_id, connection_id)
    grants: HashMap<(String, String), ConnectionGrant>,
}

pub struct AuthState {
    inner: Mutex<AuthInner>,
    /// Bumped on every revocation; snapshot it before work and compare after
    /// to catch revoke-during-operation races.
    revocation_counter: AtomicU64,
}

impl Default for AuthState {
    fn default() -> Self {
        Self {
            inner: Mutex::new(AuthInner {
                clients: HashMap::new(),
                grants: HashMap::new(),
            }),
            revocation_counter: AtomicU64::new(0),
        }
    }
}

impl AuthState {
    /// Create a new pairing. Returns (client_id, raw token). The raw token is
    /// returned exactly once and never stored.
    pub fn pair_client(&self, label: Option<String>) -> Option<(String, String)> {
        let client_id = uuid::Uuid::new_v4().to_string();
        let token = uuid::Uuid::new_v4().simple().to_string()
            + &uuid::Uuid::new_v4().simple().to_string();
        let client = PairedClient {
            client_id: client_id.clone(),
            label: label.filter(|l| !l.trim().is_empty()),
            token_hash: hash_token(&token),
            created_at_ms: now_ms(),
        };
        let mut inner = self.inner.lock().ok()?;
        inner.clients.insert(client_id.clone(), client);
        Some((client_id, token))
    }

    pub fn authenticate(&self, client_id: &str, token: &str) -> Result<(), AuthError> {
        let inner = self.inner.lock().map_err(|_| AuthError::UnknownClient)?;
        let client = inner.clients.get(client_id).ok_or(AuthError::UnknownClient)?;
        if client.token_hash != hash_token(token) {
            return Err(AuthError::BadToken);
        }
        Ok(())
    }

    /// User-driven grant: client may observe (and later, request commands on)
    /// this exact connection generation from `grant_start_seq` onward.
    pub fn grant_connection(
        &self,
        client_id: &str,
        connection_id: &str,
        generation: u64,
        grant_start_seq: u64,
    ) -> Option<ConnectionGrant> {
        let mut inner = self.inner.lock().ok()?;
        if !inner.clients.contains_key(client_id) {
            return None;
        }
        let grant = ConnectionGrant {
            grant_id: uuid::Uuid::new_v4().to_string(),
            client_id: client_id.to_string(),
            connection_id: connection_id.to_string(),
            generation,
            grant_start_seq,
            created_at_ms: now_ms(),
        };
        inner
            .grants
            .insert((client_id.to_string(), connection_id.to_string()), grant.clone());
        self.revocation_counter.fetch_add(1, Ordering::SeqCst);
        Some(grant)
    }

    /// Authorize one concrete operation. Validates the client token, the
    /// grant, and that the connection's current generation still matches the
    /// granted one.
    pub fn authorize(
        &self,
        client_id: &str,
        token: &str,
        connection_id: &str,
        current_generation: u64,
    ) -> Result<ConnectionGrant, AuthError> {
        self.authenticate(client_id, token)?;
        let inner = self.inner.lock().map_err(|_| AuthError::UnknownClient)?;
        let grant = inner
            .grants
            .get(&(client_id.to_string(), connection_id.to_string()))
            .cloned()
            .ok_or(AuthError::NoGrant)?;
        if grant.generation != current_generation {
            return Err(AuthError::StaleGeneration);
        }
        Ok(grant)
    }

    pub fn revoke(&self, client_id: &str, connection_id: &str) -> bool {
        let removed = self
            .inner
            .lock()
            .map(|mut inner| {
                inner
                    .grants
                    .remove(&(client_id.to_string(), connection_id.to_string()))
                    .is_some()
            })
            .unwrap_or(false);
        if removed {
            self.revocation_counter.fetch_add(1, Ordering::SeqCst);
        }
        removed
    }

    /// Drop every grant pointing at a connection (close/exit path).
    pub fn revoke_connection(&self, connection_id: &str) {
        let removed = self
            .inner
            .lock()
            .map(|mut inner| {
                let before = inner.grants.len();
                inner.grants.retain(|_, grant| grant.connection_id != connection_id);
                inner.grants.len() != before
            })
            .unwrap_or(false);
        if removed {
            self.revocation_counter.fetch_add(1, Ordering::SeqCst);
        }
    }

    /// Unpair a client entirely: token stops working, all its grants die.
    pub fn unpair(&self, client_id: &str) {
        let changed = self
            .inner
            .lock()
            .map(|mut inner| {
                let had_client = inner.clients.remove(client_id).is_some();
                let before = inner.grants.len();
                inner.grants.retain(|_, grant| grant.client_id != client_id);
                had_client || inner.grants.len() != before
            })
            .unwrap_or(false);
        if changed {
            self.revocation_counter.fetch_add(1, Ordering::SeqCst);
        }
    }

    #[allow(dead_code)] // retained as phase B/C integration surface
    pub fn revocation_counter(&self) -> u64 {
        self.revocation_counter.load(Ordering::SeqCst)
    }

    pub fn list_clients(&self) -> Vec<PairedClientSummary> {
        self.inner
            .lock()
            .map(|inner| {
                inner
                    .clients
                    .values()
                    .map(|client| PairedClientSummary {
                        client_id: client.client_id.clone(),
                        label: client.label.clone(),
                        created_at_ms: client.created_at_ms,
                        grants: inner
                            .grants
                            .values()
                            .filter(|grant| grant.client_id == client.client_id)
                            .map(|grant| grant.connection_id.clone())
                            .collect(),
                    })
                    .collect()
            })
            .unwrap_or_default()
    }
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct PairedClientSummary {
    pub client_id: String,
    pub label: Option<String>,
    pub created_at_ms: u64,
    pub grants: Vec<String>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn paired_token_authenticates_and_raw_token_is_never_stored() {
        let auth = AuthState::default();
        let (client_id, token) = auth.pair_client(Some("claude".into())).unwrap();
        assert!(auth.authenticate(&client_id, &token).is_ok());
        assert_eq!(
            auth.authenticate(&client_id, "wrong").unwrap_err(),
            AuthError::BadToken
        );
        assert_eq!(
            auth.authenticate("nobody", &token).unwrap_err(),
            AuthError::UnknownClient
        );
        let inner = auth.inner.lock().unwrap();
        let stored = &inner.clients.get(&client_id).unwrap().token_hash;
        assert_ne!(stored, &token);
        assert_eq!(stored.len(), 64); // sha256 hex
    }

    #[test]
    fn grants_bind_generation_and_start_seq() {
        let auth = AuthState::default();
        let (client_id, token) = auth.pair_client(None).unwrap();
        let grant = auth.grant_connection(&client_id, "conn1", 7, 42).unwrap();
        assert_eq!(grant.grant_start_seq, 42);

        assert!(auth.authorize(&client_id, &token, "conn1", 7).is_ok());
        // Reconnect bumped the generation: old grant no longer applies.
        assert_eq!(
            auth.authorize(&client_id, &token, "conn1", 8).unwrap_err(),
            AuthError::StaleGeneration
        );
        // A different connection on the same host is a different id.
        assert_eq!(
            auth.authorize(&client_id, &token, "conn2", 7).unwrap_err(),
            AuthError::NoGrant
        );
    }

    #[test]
    fn revocation_is_immediate_and_bumps_counter() {
        let auth = AuthState::default();
        let (client_id, token) = auth.pair_client(None).unwrap();
        auth.grant_connection(&client_id, "conn1", 1, 0).unwrap();
        let before = auth.revocation_counter();

        assert!(auth.revoke(&client_id, "conn1"));
        assert!(auth.revocation_counter() > before);
        assert_eq!(
            auth.authorize(&client_id, &token, "conn1", 1).unwrap_err(),
            AuthError::NoGrant
        );
    }

    #[test]
    fn unpair_kills_token_and_grants() {
        let auth = AuthState::default();
        let (client_id, token) = auth.pair_client(None).unwrap();
        auth.grant_connection(&client_id, "conn1", 1, 0).unwrap();
        auth.unpair(&client_id);
        assert_eq!(
            auth.authenticate(&client_id, &token).unwrap_err(),
            AuthError::UnknownClient
        );
        assert_eq!(
            auth.authorize(&client_id, &token, "conn1", 1).unwrap_err(),
            AuthError::UnknownClient
        );
    }

    #[test]
    fn revoke_connection_drops_all_client_grants_for_it() {
        let auth = AuthState::default();
        let (a, token_a) = auth.pair_client(None).unwrap();
        let (b, token_b) = auth.pair_client(None).unwrap();
        auth.grant_connection(&a, "conn1", 1, 0).unwrap();
        auth.grant_connection(&b, "conn1", 1, 0).unwrap();
        auth.grant_connection(&b, "conn2", 1, 0).unwrap();

        auth.revoke_connection("conn1");
        assert!(auth.authorize(&a, &token_a, "conn1", 1).is_err());
        assert!(auth.authorize(&b, &token_b, "conn1", 1).is_err());
        assert!(auth.authorize(&b, &token_b, "conn2", 1).is_ok());
    }
}
