//! MCP client pairing and per-connection authorization (phase B, ORQ-29).
//!
//! - Clients pair once with a random token generated by the app. Only a
//!   SHA-256 hash is kept in memory; the raw token is shown to the user a
//!   single time and never written to disk, WebDAV or the repository.
//! - A paired client holds no power until the user grants it access to one
//!   specific connection generation. Grants bind (client, connection,
//!   generation) so a reconnect of the same host never inherits old access.
//! - Every grant records the output sequence at authorization time; agents
//!   can only read output produced after the grant, never scrollback from
//!   before it.
//! - Revocation is immediate and monotonic (`revocation_counter` bumps
//!   invalidate in-flight checks).

use serde::Serialize;
use sha2::{Digest, Sha256};
use std::collections::HashMap;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Mutex;

fn now_ms() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

fn hash_token(token: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(token.as_bytes());
    format!("{:x}", hasher.finalize())
}

#[derive(Debug, Clone)]
pub struct PairedClient {
    pub client_id: String,
    /// Human-readable name captured at pairing time. Used for display only;
    /// never for identity decisions (clients could lie about it).
    pub label: Option<String>,
    token_hash: String,
    pub created_at_ms: u64,
}

#[derive(Debug, Clone)]
#[allow(dead_code)] // retained as phase B/C integration surface
pub struct ConnectionGrant {
    pub grant_id: String,
    pub client_id: String,
    pub connection_id: String,
    pub generation: u64,
    /// First output sequence the client may read for this connection.
    pub grant_start_seq: u64,
    pub created_at_ms: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AuthError {
    UnknownClient,
    BadToken,
    NoGrant,
    StaleGeneration,
}

struct AuthInner {
    clients: HashMap<String, PairedClient>,
    /// grants keyed by (client_id, connection_id)
    grants: HashMap<(String, String), ConnectionGrant>,
}

pub struct AuthState {
    inner: Mutex<AuthInner>,
    /// Bumped on every revocation; snapshot it before work and compare after
    /// to catch revoke-during-operation races.
    revocation_counter: AtomicU64,
    /// Optional SQLite persistence. In-memory only when None (tests); the
    /// app opens `<config>/mcp.db` so pairings survive restarts. The DB
    /// lives in the app config dir and is deliberately NOT the
    /// WebDAV-synced hosts.db: pairing secrets never leave this machine.
    db: Option<Mutex<rusqlite::Connection>>,
}

impl Default for AuthState {
    fn default() -> Self {
        Self::in_memory()
    }
}

impl AuthState {
    /// No persistence: for unit tests only.
    pub fn in_memory() -> Self {
        Self {
            inner: Mutex::new(AuthInner {
                clients: HashMap::new(),
                grants: HashMap::new(),
            }),
            revocation_counter: AtomicU64::new(0),
            db: None,
        }
    }
    /// Open (and initialize) the persistent pairing store.
    pub fn open(db_path: &std::path::Path) -> Result<Self, String> {
        if let Some(parent) = db_path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
        }
        let conn = rusqlite::Connection::open(db_path).map_err(|e| e.to_string())?;
        conn.busy_timeout(std::time::Duration::from_secs(5))
            .map_err(|e| e.to_string())?;
        conn.execute_batch(
            "CREATE TABLE IF NOT EXISTS mcp_clients (
               client_id     TEXT PRIMARY KEY,
               label         TEXT,
               token_hash    TEXT NOT NULL,
               created_at_ms INTEGER NOT NULL
             );
             CREATE TABLE IF NOT EXISTS mcp_grants (
               client_id       TEXT NOT NULL,
               connection_id   TEXT NOT NULL,
               generation      INTEGER NOT NULL,
               grant_start_seq INTEGER NOT NULL,
               created_at_ms   INTEGER NOT NULL,
               PRIMARY KEY (client_id, connection_id)
             );",
        )
        .map_err(|e| e.to_string())?;

        let mut inner = AuthInner {
            clients: HashMap::new(),
            grants: HashMap::new(),
        };
        {
            let mut stmt = conn
                .prepare("SELECT client_id, label, token_hash, created_at_ms FROM mcp_clients")
                .map_err(|e| e.to_string())?;
            let rows = stmt
                .query_map([], |row| {
                    Ok(PairedClient {
                        client_id: row.get(0)?,
                        label: row.get(1)?,
                        token_hash: row.get(2)?,
                        created_at_ms: row.get(3)?,
                    })
                })
                .map_err(|e| e.to_string())?;
            for client in rows {
                let client = client.map_err(|e| e.to_string())?;
                inner.clients.insert(client.client_id.clone(), client);
            }
        }
        {
            let mut stmt = conn
                .prepare(
                    "SELECT client_id, connection_id, generation, grant_start_seq, created_at_ms
                     FROM mcp_grants",
                )
                .map_err(|e| e.to_string())?;
            let rows = stmt
                .query_map([], |row| {
                    Ok(ConnectionGrant {
                        grant_id: String::new(), // regenerated below
                        client_id: row.get(0)?,
                        connection_id: row.get(1)?,
                        generation: row.get(2)?,
                        grant_start_seq: row.get(3)?,
                        created_at_ms: row.get(4)?,
                    })
                })
                .map_err(|e| e.to_string())?;
            for grant in rows {
                let mut grant = grant.map_err(|e| e.to_string())?;
                grant.grant_id = uuid::Uuid::new_v4().to_string();
                inner
                    .grants
                    .insert((grant.client_id.clone(), grant.connection_id.clone()), grant);
            }
        }

        Ok(Self {
            inner: Mutex::new(inner),
            revocation_counter: AtomicU64::new(0),
            db: Some(Mutex::new(conn)),
        })
    }

    /// Preferred app entry point: persistent store with graceful fallback to
    /// in-memory when the DB cannot be opened (MCP must never take the app
    /// down; it just loses pairing across restarts).
    pub fn open_or_memory(db_path: &std::path::Path) -> Self {
        match Self::open(db_path) {
            Ok(state) => state,
            Err(error) => {
                eprintln!("[mcp] pairing store unavailable, using memory only: {error}");
                Self::in_memory()
            }
        }
    }

    fn mcp_db_path() -> std::path::PathBuf {
        crate::ssh_config::get_ssh_config_path()
            .parent()
            .unwrap_or_else(|| std::path::Path::new("."))
            .join("mcp.db")
    }

    /// App entry point using the default store location.
    pub fn open_default() -> Self {
        Self::open_or_memory(&Self::mcp_db_path())
    }

    fn persist_client(&self, client: &PairedClient) {
        let Some(db) = self.db.as_ref() else { return };
        let Ok(conn) = db.lock() else { return };
        let _ = conn.execute(
            "INSERT INTO mcp_clients (client_id, label, token_hash, created_at_ms)
             VALUES (?1, ?2, ?3, ?4)
             ON CONFLICT(client_id) DO UPDATE SET label=?2, token_hash=?3, created_at_ms=?4",
            rusqlite::params![
                client.client_id,
                client.label,
                client.token_hash,
                client.created_at_ms
            ],
        );
    }

    fn persist_delete_client(&self, client_id: &str) {
        let Some(db) = self.db.as_ref() else { return };
        let Ok(conn) = db.lock() else { return };
        let _ = conn.execute("DELETE FROM mcp_clients WHERE client_id = ?1", [client_id]);
        let _ = conn.execute("DELETE FROM mcp_grants WHERE client_id = ?1", [client_id]);
    }

    fn persist_grant(&self, grant: &ConnectionGrant) {
        let Some(db) = self.db.as_ref() else { return };
        let Ok(conn) = db.lock() else { return };
        let _ = conn.execute(
            "INSERT INTO mcp_grants (client_id, connection_id, generation, grant_start_seq, created_at_ms)
             VALUES (?1, ?2, ?3, ?4, ?5)
             ON CONFLICT(client_id, connection_id) DO UPDATE SET
               generation=?3, grant_start_seq=?4, created_at_ms=?5",
            rusqlite::params![
                grant.client_id,
                grant.connection_id,
                grant.generation as i64,
                grant.grant_start_seq as i64,
                grant.created_at_ms
            ],
        );
    }

    fn persist_delete_grant(&self, client_id: &str, connection_id: &str) {
        let Some(db) = self.db.as_ref() else { return };
        let Ok(conn) = db.lock() else { return };
        let _ = conn.execute(
            "DELETE FROM mcp_grants WHERE client_id = ?1 AND connection_id = ?2",
            [client_id, connection_id],
        );
    }

    fn persist_delete_grants_for_connection(&self, connection_id: &str) {
        let Some(db) = self.db.as_ref() else { return };
        let Ok(conn) = db.lock() else { return };
        let _ = conn.execute(
            "DELETE FROM mcp_grants WHERE connection_id = ?1",
            [connection_id],
        );
    }

    /// Create a new pairing. Returns (client_id, raw token). The raw token is
    /// returned exactly once and never stored.
    pub fn pair_client(&self, label: Option<String>) -> Option<(String, String)> {
        let client_id = uuid::Uuid::new_v4().to_string();
        let token = uuid::Uuid::new_v4().simple().to_string()
            + &uuid::Uuid::new_v4().simple().to_string();
        let client = PairedClient {
            client_id: client_id.clone(),
            label: label.filter(|l| !l.trim().is_empty()),
            token_hash: hash_token(&token),
            created_at_ms: now_ms(),
        };
        let mut inner = self.inner.lock().ok()?;
        inner.clients.insert(client_id.clone(), client.clone());
        drop(inner);
        self.persist_client(&client);
        Some((client_id, token))
    }

    pub fn authenticate(&self, client_id: &str, token: &str) -> Result<(), AuthError> {
        let inner = self.inner.lock().map_err(|_| AuthError::UnknownClient)?;
        let client = inner.clients.get(client_id).ok_or(AuthError::UnknownClient)?;
        if client.token_hash != hash_token(token) {
            return Err(AuthError::BadToken);
        }
        Ok(())
    }

    /// User-driven grant: client may observe (and later, request commands on)
    /// this exact connection generation from `grant_start_seq` onward.
    pub fn grant_connection(
        &self,
        client_id: &str,
        connection_id: &str,
        generation: u64,
        grant_start_seq: u64,
    ) -> Option<ConnectionGrant> {
        let mut inner = self.inner.lock().ok()?;
        if !inner.clients.contains_key(client_id) {
            return None;
        }
        let grant = ConnectionGrant {
            grant_id: uuid::Uuid::new_v4().to_string(),
            client_id: client_id.to_string(),
            connection_id: connection_id.to_string(),
            generation,
            grant_start_seq,
            created_at_ms: now_ms(),
        };
        inner
            .grants
            .insert((client_id.to_string(), connection_id.to_string()), grant.clone());
        drop(inner);
        self.persist_grant(&grant);
        self.revocation_counter.fetch_add(1, Ordering::SeqCst);
        Some(grant)
    }

    /// Authorize one concrete operation. Validates the client token, the
    /// grant, and that the connection's current generation still matches the
    /// granted one.
    pub fn authorize(
        &self,
        client_id: &str,
        token: &str,
        connection_id: &str,
        current_generation: u64,
    ) -> Result<ConnectionGrant, AuthError> {
        self.authenticate(client_id, token)?;
        let inner = self.inner.lock().map_err(|_| AuthError::UnknownClient)?;
        let grant = inner
            .grants
            .get(&(client_id.to_string(), connection_id.to_string()))
            .cloned()
            .ok_or(AuthError::NoGrant)?;
        if grant.generation != current_generation {
            return Err(AuthError::StaleGeneration);
        }
        Ok(grant)
    }

    pub fn revoke(&self, client_id: &str, connection_id: &str) -> bool {
        let removed = self
            .inner
            .lock()
            .map(|mut inner| {
                inner
                    .grants
                    .remove(&(client_id.to_string(), connection_id.to_string()))
                    .is_some()
            })
            .unwrap_or(false);
        if removed {
            self.persist_delete_grant(client_id, connection_id);
            self.revocation_counter.fetch_add(1, Ordering::SeqCst);
        }
        removed
    }

    /// Drop every grant pointing at a connection (close/exit path).
    pub fn revoke_connection(&self, connection_id: &str) {
        let removed = self
            .inner
            .lock()
            .map(|mut inner| {
                let before = inner.grants.len();
                inner.grants.retain(|_, grant| grant.connection_id != connection_id);
                inner.grants.len() != before
            })
            .unwrap_or(false);
        if removed {
            self.persist_delete_grants_for_connection(connection_id);
            self.revocation_counter.fetch_add(1, Ordering::SeqCst);
        }
    }

    /// Unpair a client entirely: token stops working, all its grants die.
    pub fn unpair(&self, client_id: &str) {
        let changed = self
            .inner
            .lock()
            .map(|mut inner| {
                let had_client = inner.clients.remove(client_id).is_some();
                let before = inner.grants.len();
                inner.grants.retain(|_, grant| grant.client_id != client_id);
                had_client || inner.grants.len() != before
            })
            .unwrap_or(false);
        if changed {
            self.persist_delete_client(client_id);
            self.revocation_counter.fetch_add(1, Ordering::SeqCst);
        }
    }

    #[allow(dead_code)] // retained as phase B/C integration surface
    pub fn revocation_counter(&self) -> u64 {
        self.revocation_counter.load(Ordering::SeqCst)
    }

    pub fn list_clients(&self) -> Vec<PairedClientSummary> {
        self.inner
            .lock()
            .map(|inner| {
                inner
                    .clients
                    .values()
                    .map(|client| PairedClientSummary {
                        client_id: client.client_id.clone(),
                        label: client.label.clone(),
                        created_at_ms: client.created_at_ms,
                        grants: inner
                            .grants
                            .values()
                            .filter(|grant| grant.client_id == client.client_id)
                            .map(|grant| grant.connection_id.clone())
                            .collect(),
                    })
                    .collect()
            })
            .unwrap_or_default()
    }
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct PairedClientSummary {
    pub client_id: String,
    pub label: Option<String>,
    pub created_at_ms: u64,
    pub grants: Vec<String>,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_db(tag: &str) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "xt-auth-{}-{tag}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir.join("mcp.db")
    }

    #[test]
    fn pairing_and_grants_survive_restart() {
        let db = temp_db("survive");
        {
            let auth = AuthState::open(&db).unwrap();
            let (client_id, token) = auth.pair_client(Some("claude".into())).unwrap();
            auth.grant_connection(&client_id, "conn-1", 7, 42).unwrap();
            // simulate restart: drop everything
        }
        let auth = AuthState::open(&db).unwrap();
        let clients = auth.list_clients();
        assert_eq!(clients.len(), 1);
        assert_eq!(clients[0].label.as_deref(), Some("claude"));
        assert_eq!(clients[0].grants, vec!["conn-1".to_string()]);

        // Raw token still authenticates (hash persisted, not the token).
        let client_id = &clients[0].client_id;
        // token was dropped with the first instance; re-derive by pairing a
        // second client and verifying a restart keeps BOTH clients working.
        let (_id2, token2) = auth.pair_client(None).unwrap();
        drop(auth);
        let auth = AuthState::open(&db).unwrap();
        assert!(auth.authenticate(&_id2, &token2).is_ok());
        assert_eq!(auth.list_clients().len(), 2);
        // Grant reloaded with the right generation/start seq.
        assert!(auth.authorize(client_id, "", "conn-1", 7).is_err()); // empty token -> BadToken, proves client exists
    }

    #[test]
    fn unpair_and_revoke_persist() {
        let db = temp_db("revoke");
        let (client_id, token) = {
            let auth = AuthState::open(&db).unwrap();
            let (client_id, token) = auth.pair_client(None).unwrap();
            auth.grant_connection(&client_id, "conn-1", 1, 0).unwrap();
            (client_id, token)
        };
        {
            let auth = AuthState::open(&db).unwrap();
            assert!(auth.authenticate(&client_id, &token).is_ok());
            assert!(auth.revoke(&client_id, "conn-1"));
        }
        let auth = AuthState::open(&db).unwrap();
        assert_eq!(
            auth.authorize(&client_id, &token, "conn-1", 1).unwrap_err(),
            AuthError::NoGrant
        );
        auth.unpair(&client_id);
        drop(auth);
        let auth = AuthState::open(&db).unwrap();
        assert_eq!(
            auth.authenticate(&client_id, &token).unwrap_err(),
            AuthError::UnknownClient
        );
        assert!(auth.list_clients().is_empty());
    }

    #[test]
    fn connection_revoke_persists_across_restart() {
        let db = temp_db("connrevoke");
        let (a, ta) = {
            let auth = AuthState::open(&db).unwrap();
            let (a, ta) = auth.pair_client(None).unwrap();
            let (b, _tb) = auth.pair_client(None).unwrap();
            auth.grant_connection(&a, "conn-1", 1, 0).unwrap();
            auth.grant_connection(&b, "conn-1", 1, 0).unwrap();
            auth.grant_connection(&b, "conn-2", 1, 0).unwrap();
            auth.revoke_connection("conn-1");
            (a, ta)
        };
        let auth = AuthState::open(&db).unwrap();
        assert_eq!(
            auth.authorize(&a, &ta, "conn-1", 1).unwrap_err(),
            AuthError::NoGrant
        );
        // conn-2 grant survived (only conn-1 was revoked).
        assert_eq!(auth.list_clients().len(), 2);
    }

    #[test]
    fn open_or_memory_falls_back_gracefully() {
        // A path that cannot be a database (a directory) must not panic.
        let dir = temp_db("fallback");
        std::fs::create_dir_all(&dir).unwrap();
        let auth = AuthState::open_or_memory(&dir); // dir itself, not a file
        let (client_id, token) = auth.pair_client(None).unwrap();
        assert!(auth.authenticate(&client_id, &token).is_ok());
    }

    #[test]
    fn paired_token_authenticates_and_raw_token_is_never_stored() {
        let auth = AuthState::default();
        let (client_id, token) = auth.pair_client(Some("claude".into())).unwrap();
        assert!(auth.authenticate(&client_id, &token).is_ok());
        assert_eq!(
            auth.authenticate(&client_id, "wrong").unwrap_err(),
            AuthError::BadToken
        );
        assert_eq!(
            auth.authenticate("nobody", &token).unwrap_err(),
            AuthError::UnknownClient
        );
        let inner = auth.inner.lock().unwrap();
        let stored = &inner.clients.get(&client_id).unwrap().token_hash;
        assert_ne!(stored, &token);
        assert_eq!(stored.len(), 64); // sha256 hex
    }

    #[test]
    fn grants_bind_generation_and_start_seq() {
        let auth = AuthState::default();
        let (client_id, token) = auth.pair_client(None).unwrap();
        let grant = auth.grant_connection(&client_id, "conn1", 7, 42).unwrap();
        assert_eq!(grant.grant_start_seq, 42);

        assert!(auth.authorize(&client_id, &token, "conn1", 7).is_ok());
        // Reconnect bumped the generation: old grant no longer applies.
        assert_eq!(
            auth.authorize(&client_id, &token, "conn1", 8).unwrap_err(),
            AuthError::StaleGeneration
        );
        // A different connection on the same host is a different id.
        assert_eq!(
            auth.authorize(&client_id, &token, "conn2", 7).unwrap_err(),
            AuthError::NoGrant
        );
    }

    #[test]
    fn revocation_is_immediate_and_bumps_counter() {
        let auth = AuthState::default();
        let (client_id, token) = auth.pair_client(None).unwrap();
        auth.grant_connection(&client_id, "conn1", 1, 0).unwrap();
        let before = auth.revocation_counter();

        assert!(auth.revoke(&client_id, "conn1"));
        assert!(auth.revocation_counter() > before);
        assert_eq!(
            auth.authorize(&client_id, &token, "conn1", 1).unwrap_err(),
            AuthError::NoGrant
        );
    }

    #[test]
    fn unpair_kills_token_and_grants() {
        let auth = AuthState::default();
        let (client_id, token) = auth.pair_client(None).unwrap();
        auth.grant_connection(&client_id, "conn1", 1, 0).unwrap();
        auth.unpair(&client_id);
        assert_eq!(
            auth.authenticate(&client_id, &token).unwrap_err(),
            AuthError::UnknownClient
        );
        assert_eq!(
            auth.authorize(&client_id, &token, "conn1", 1).unwrap_err(),
            AuthError::UnknownClient
        );
    }

    #[test]
    fn revoke_connection_drops_all_client_grants_for_it() {
        let auth = AuthState::default();
        let (a, token_a) = auth.pair_client(None).unwrap();
        let (b, token_b) = auth.pair_client(None).unwrap();
        auth.grant_connection(&a, "conn1", 1, 0).unwrap();
        auth.grant_connection(&b, "conn1", 1, 0).unwrap();
        auth.grant_connection(&b, "conn2", 1, 0).unwrap();

        auth.revoke_connection("conn1");
        assert!(auth.authorize(&a, &token_a, "conn1", 1).is_err());
        assert!(auth.authorize(&b, &token_b, "conn1", 1).is_err());
        assert!(auth.authorize(&b, &token_b, "conn2", 1).is_ok());
    }
}
